version: '3'
services:
  db:
    container_name: postgres-trpc-blog
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: blog
      POSTGRES_DB: blog
    volumes: 
      - .dbdata:/var/lib/postgres 
    expose:
      - 5432
